### ISSUE TITLE
Why two spaces are used in strings instead of just one?

### ISSUE THREAD

**Issue by hankcs** [telepathylabsai/OpenDF#10]
Dear authors,

I have a question that is not so critical but it's a little bit confusing. I saw SQL generated by OpenDF are using double spaces in every string. As a result, I have to use double spaces in person names, topic etc., which is not convenient  for debugging. 

E.g.,

```
SELECT event.id,
       event.subject,
       event.starts_at,
       event.ends_at,
       event.location_id,
       event.organizer_id,
       location.name,
       location.always_free
FROM event
         LEFT OUTER JOIN location ON event.location_id = location.id
WHERE (event.subject LIKE '%dinner  reservation%' AND date(event.starts_at) = date('2022-01-06') AND
       ((time(event.starts_at) >= time('17:00:00') AND time(event.starts_at) <= time('21:30:00')) OR
        (time(event.ends_at) >= time('17:00:00') AND time(event.ends_at) <= time('21:30:00')) OR
        (time(event.starts_at) <= time('17:00:00') AND time(event.ends_at) >= time('17:00:00')) OR
        (time(event.starts_at) <= time('21:30:00') AND time(event.ends_at) >= time('21:30:00'))))
```

`dinner reservation` won't be matched.

**Comment by guimaraes-tl** [comment]
Dear hankcs,

I'm not sure if I can reproduce this problem.

Note: In the message below, I replaced space by *, because multiple following spaces don't seem to be shown in the GitHub message preview.

I tried the expression `FindEvents(has_subject(dinner*reservation))` and the generated SQL was:

```
SELECT 
    event.id, 
    event.subject, 
    event.starts_at, 
    event.ends_at, 
    event.location_id, 
    event.organizer_id, 
    location.name, 
    location.always_free 
FROM event 
    LEFT OUTER JOIN location ON event.location_id = location.id 
WHERE event.subject LIKE '%dinner*reservation%'
```

Single space in the expression `dinner*reservation` and in the SQL where clause `LIKE '%dinner*reservation%'`.

If I try `FindEvents(has_subject(dinner**reservation))`, with two spaces on the expression, the SQL changes accordingly to 
`... LIKE '%dinner**reservation%'` (two spaces) in the where clause.

Maybe the additional spaces are in the expression? Or maybe you can provide me the expression, so I can try with it.

Best regards.

**Comment by hankcs** [comment]
Thanks for your prompt reply. 

Sure, no problem. I didn't see `*` in all simplified expressions:

```
 GTf(
    size(
       FindEvents(
          AND(
             starts_at(
                Today(
                   ) ) ,
             with_attendee(
                Steven ) ,
             has_subject(
                performance evaluation ) ) ) ) ,
    0 ) 
```

The generated SQL was:

```
SELECT event.id,
       event.subject,
       event.starts_at,
       event.ends_at,
       event.location_id,
       event.organizer_id,
       location.name,
       location.always_free
FROM event
         LEFT OUTER JOIN location ON event.location_id = location.id
WHERE (date(event.starts_at) = date('2022-01-03') AND event.id IN (SELECT event_has_attendee.event_id
                                                                   FROM event_has_attendee
                                                                            JOIN recipient ON recipient.id = event_has_attendee.recipient_id
                                                                   WHERE recipient.id = 1009) AND
       event.subject LIKE '%performance  evaluation%')
```
You can see there're two spaces.

**Comment by guimaraes-tl** [comment]
Hello hankcs, 

The simplification process was adding some additional spaces, we fixed it.
Also, we now replace multiple spaces within parsed strings by single space.

This example should work now.

Best regards.

**Comment by hankcs** [comment]
Great, thank you so much!
