### ISSUE TITLE
"I could not find a matching time." Exception

### ISSUE THREAD

**Issue by hankcs** [telepathylabsai/OpenDF#15]
Dear authors,

I'm having a strange problem that OpenDF said "I could not find a matching time" even if the calendar is almost empty. E.g,

## Dialog 39

**GUID**: `b8e3f6eb-88a2-4467-8ba2-74da83b1c09e` **OpenDF**:

 - U1: Create an event for 6 AM tomorrow: "Print flight tickets"
 - A1: I've put that on your calendar. Your status is set to Busy.
 - U2: Schedule flight the day **after that** at 7 pm.
 - A2: I've put that on your calendar. Your status is set to Busy.

Program:

```
 CreateEvent(
    AND(
       has_subject(
          Print flight tickets ) ,
       starts_at(
          Tomorrow(
             ) ) ,
       starts_at(
          NumberAM(
             6 ) ) ) )

 CreateEvent(
    AND(
       has_subject(
          flight ) ,
       starts_at(
          adjustByPeriod(
             refer(
                Date?(
                   ) ) ,
             toDays(
                1 ) ) ) ,
       starts_at(
          NumberPM(
             7 ) ) ) ) 
```

Database after execution:
![Screen Shot 2022-06-21 at 10 19 19 AM](https://user-images.githubusercontent.com/5326890/174822584-0a774e68-b09a-4b0c-80ba-cdbe36578439.png)

Graphs:
[39.dot.pdf](https://github.com/telepathylabsai/OpenDF/files/8949747/39.dot.pdf)

After the second turn, OpenDF raised `I could not find a matching time. Do you have a suggestion?` which doesn't make sense to me. Could you help me out?

**Comment by meron-tl** [comment]
Fixed AdjustByDuration to return either Date or DateTime.  commit f6e7a0d9
Previously, for Date input, it returned a DateTime with time set to 0:00

**Comment by hankcs** [comment]
Thanks, it fixed the issue.
