### ISSUE TITLE
opendf.exceptions.df_exception.MultipleEntriesSingletonException

### ISSUE THREAD

**Issue by hankcs** [telepathylabsai/OpenDF#16]
Dear authors,

I found a dialog that OpenDF cannot execute due to `MultipleEntriesSingletonException`.

## Dialog 47

**GUID**: `e13711b6-e221-416b-81e6-2a4bdfdc72a7` **OpenDF**:

 - U1: Can you see if my manager if the organizer of dance show
 - A1: Yes. David Lax is the organizer of "Dance Show".
 - U2: Interesting. Is my manager the organizer of the event right **after that**?
 - A2: Yes, David is the organizer of "Dance Show afterparty".

Database:
![Screen Shot 2022-06-21 at 10 50 49 AM](https://user-images.githubusercontent.com/5326890/174829886-bab5bf6b-049e-4fb1-a81f-2a1b8d883464.png)

I know since there're 2 events matching `Dance Show` so OpenDF raised `MultipleEntriesSingletonException` when executing `singleton`. However, wouldn't it be better for singleton to just take the first event since SMCalFlow's engine is able to execute this program?

**Comment by hankcs** [comment]
Same issue with this one:

## Dialog 61

**GUID**: `27590713-b4ea-4da2-ba9b-dbdeee154adc` **OpenDF**:

 - U1: Will I be attending the Gala tonight?
 - A1: You are the organizer of "Gala".
 - U2: Did I accept the meeting **before the** Gala?
 - A2: Yes, you have accepted the "meeting **before the** Gala" invitation.
 - U3: Are we going to the New Years Bash?
 - A3: Yes, you have accepted the "New Years Bash" invitation.

**Comment by hankcs** [comment]
Another instance:

## Dialog 74

**GUID**: `42269e5c-c900-404a-83ff-2b7500da0503` **OpenDF**:

 - U1: Schedule dentist appoint this Tues for 2 hours at 1pm.
 - A1: I've put that on your calendar. Your status is set to Busy.
 - U2: What do I have scheduled **after the** appointment?
 - A2: I didn't find any events on Tuesday after 3:00.
 - U3: What are my dinner plans **after that**?
 - A3: I didn't find any events matching "dinner plans" on Tuesday the 18th after 3:00.

This one is interesting because there is only one event on the calendar but OpenDF still raises 

```
opendf.exceptions.df_exception.MultipleEntriesSingletonException: Multiple Event objects NL 2 Events NL meeting starting tomorrow NL 15:00 NL 
```

Program:

```

 CreateEvent(
    AND(
       has_duration(
          toHours(
             2 ) ) ,
       has_subject(
          dentist appoint ) ,
       starts_at(
          NextDOW(
             TUESDAY ) ) ,
       starts_at(
          NumberPM(
             1 ) ) ) ) 

 do(
    Let(
       x0 ,
       :end(
          refer(
             Event?(
                ) ) ) ) ,
    FindEvents(
       AND(
          starts_at(
             :date(
                $ x0 ) ) ,
          starts_at(
             GT(
                :time(
                   $ x0 ) ) ) ) ) ) 

 do(
    Let(
       x0 ,
       :end(
          refer(
             Event?(
                ) ) ) ) ,
    FindEvents(
       AND(
          has_subject(
             dinner plans ) ,
          starts_at(
             :date(
                $ x0 ) ) ,
          starts_at(
             GT(
                :time(
                   $ x0 ) ) ) ) ) ) 
```

**Comment by meron-tl** [comment]
For the last example - the match function for an operator object was fixed. please try commit  7672711e.

**Comment by hankcs** [comment]
Yes, I agree. There are some myths hidden in MS' implementation of `singleton` . Looking at the first example, no such APIs are used to choose which "show" should be returned, but somehow their implementation figures out it's the second. So, I agree with you they could have done some commonsense magic  somewhere.

**Comment by hankcs** [comment]
> For the last example - the match function for an operator object was fixed. please try commit [7672711](https://github.com/telepathylabsai/OpenDF/commit/7672711ea144a4c2115e2fe155040562766f642c).

Thanks, fix confirmed.
