### ISSUE TITLE
Wrongly Simplified Graph with Semantics Missing

### ISSUE THREAD

**Issue by hankcs** [telepathylabsai/OpenDF#3]
Dear authors,

After more experiments on OpenDF, I noticed a wrongly simplified graph that some semantics from SMCalFlow is missing. Its turns are like this:

1. What time is my train tomorrow?
2. You have one event on your calendar. Your "train" is tomorrow from 3:00 to 3:30 PM.
3. *After that* set family time from 4 and make sure there isn't anything else on the schedule.
4. I've put that on your calendar. Your status is set to Busy.

In utterance 3, SMCalFlow correctly annotated that the date of "family time" needs to match the date of "train", which is a reference and needs to be resolved. As highlighted in the red box, DF correctly annotated the date of “family time” in utterance 3 is the end day of “train” event.
![Screen Shot 2022-06-09 at 2 43 39 PM](https://user-images.githubusercontent.com/5326890/172952096-54f8dcc4-d9f2-4071-b71d-f3fcacfb9613.png)

However, OpenDF failed to convert the date part into its simplified graph, leading to mismatch semantics in its compiled/executed graphs too.

![Screen Shot 2022-06-09 at 2 49 03 PM](https://user-images.githubusercontent.com/5326890/172952168-9ccb5e8c-342d-4dd5-a601-1c9a7448ea01.png)

I don't know how many such graphs are there but I assume it's not a unique case. I'm wondering if there is a way to fix it. I'd appreciate it if you can offer some suggestions.

Thank you.

**Comment by hankcs** [comment]
For a quick reference, the dialog is:

```
{'dialogue_id': '711e9573-a9c1-49cb-a887-da7258638e7a', 'turns': [{'agent_utterance': {'described_entities': [], 'original_text': 'You have one event on your calendar. Your "train" is tomorrow from 3:00 to 3:30 PM.', 'tokens': ['You', 'have', 'one', 'event', 'on', 'your', 'calendar', '.', 'Your', '"', 'train', '"', 'is', 'tomorrow', 'from', '3', ':', '00', 'to', '3', ':', '30', 'PM', '.']}, 'lispress': '(Yield :output (FindEventWrapperWithDefaults :constraint (EventOnDate :date (Tomorrow) :event (Constraint[Event] :subject (?~= #(String "train"))))))', 'program_execution_oracle': {'has_exception': False, 'refer_are_correct': True}, 'skip': True, 'turn_index': 0, 'user_utterance': {'original_text': 'What time is my train tomorrow?', 'tokens': ['What', 'time', 'is', 'my', 'train', 'tomorrow', '?']}}, {'agent_utterance': {'described_entities': [], 'original_text': "I've put that on your calendar. Your status is set to Busy.", 'tokens': ['I', "'ve", 'put', 'that', 'on', 'your', 'calendar', '.', 'Your', 'status', 'is', 'set', 'to', 'Busy', '.']}, 'lispress': '(Yield :output (CreateCommitEventWrapper :event (CreatePreflightEventWrapper :constraint (Constraint[Event] :start (?= (TimeAfterDateTime :dateTime (:end (Execute :intension (refer (extensionConstraint (Constraint[Event]))))) :time (NumberPM :number #(Number 4)))) :subject (?= #(String "family time"))))))', 'program_execution_oracle': {'has_exception': False, 'refer_are_correct': True}, 'skip': True, 'turn_index': 1, 'user_utterance': {'original_text': "After that set family time from 4 and make sure there isn't anything else on the schedule.", 'tokens': ['After', 'that', 'set', 'family', 'time', 'from', '4', 'and', 'make', 'sure', 'there', 'is', "n't", 'anything', 'else', 'on', 'the', 'schedule', '.']}}]}
```

**Comment by meron-tl** [comment]
Thanks for raising this issue. We'll look into this and try to resolve it.

**Comment by meron-tl** [comment]
The simplification of TimeAfterDateTime was fixed. Please try again with the new version (afe7140e).
