### ISSUE TITLE
How to Implement Nodes that Are Not Implemented Yet?

### ISSUE THREAD

**Issue by hankcs** [telepathylabsai/OpenDF#4]
Dear authors,

I've read your paper and I'm aware that simplification is one of your major contributions and the execution engine is an ongoing process. I tried to execute some simplified dialogs and I noticed some functions are not implemented yet. E.g.,

* Can you create an event right *after the* last event on my calender for 2 hours?
* Is this good?

```
opendf.exceptions.python_exception.UnknownNodeTypeException: No such node type: FindLastEventn
```

* Create a new event at 6 weeks *after the* next staff meeting for HR reviews
* Is this good?

```
opendf.exceptions.python_exception.UnknownNodeTypeException: No such node type: adjustByPeriodDuration
```
Could you offer some suggestions? Also I'm willing to contribute to this open source project if needed.

**Comment by guimaraes-tl** [comment]
Dear hankcs,

We added a README.contribute.md file in the commit [ed8442d](https://github.com/telepathylabsai/OpenDF/commit/ed8442d112c469a2b08425276b6e83ae7364d133).

It provides some explanation on how to implement new nodes.

We are still working on the policy to accept new contributions, but you can start implementing new nodes/applications if you wish.

Please, fell free to put any questions you might have, we will be happy to answer them and to update the README accordingly. 

Best regards.

**Comment by hankcs** [comment]
Thank you so much. It's very helpful. I'll start with implementing nodes from SMCalFlow like `TimeAfterDateTime`.

**Comment by meron-tl** [comment]
Yes, you can do that.

One way to go about implementing a missing/new node is to look for (whole) dialogues (in the SMCalFlow dataset), where that node is used, and then implementing the whole dialogue. In this way, you get to see how the nodes work together, in a context where it's (usually) clear what task they should be doing.

Please remember that the released implementation is for the simplified annotations - so it may be best to look at the simplified version of SMCalFlow when picking nodes to implement, as some original SMCalFlow nodes are not used in the simplified expressions.

After you feel comfortable with that, you could also try modifying the simplification rules, to cover some original nodes which may not be covered, or not covered completely.

And finally - feel free to experiment and change the implementation of existing nodes / the core DF system. There are many alternative designs possible, and we'd be happy to find new ones.
