### ISSUE TITLE
ParserException: Syntax error at `LexToken(ASSIGN_NODE,'$',1,92)`

### ISSUE THREAD

**Issue by hankcs** [telepathylabsai/OpenDF#5]
Dear authors,

I don't mean to post too many issues but this one seems to be a different type. I noticed if a simplified expression contains variables then OpenDF won't be able to parse it. E.g.,

Dialog:

* When is my presentation next week?
* The "budgeting presentation" is on Wednesday the 20th from 2:00 to 3:00 PM.
* Do I have anything schedule *after that*?
* No, I didn't find any events on Wednesday the 20th after 3:00.

Expressions:
```
 FindEvents(
    AND(
       at_time(
          NextWeekList(
             ) ) ,
       has_subject(
          presentation ) ) ) 
          
  do(
    Let(
       x0 ,
       :end(
          refer(
             Event?(
                ) ) ) ) ,
    GTf(
       size(
          FindEvents(
             AND(
                starts_at(
                   :date(
                      $ x0 ) ) ,
                starts_at(
                   GT(
                      :time(
                         $ x0 ) ) ) ) ) ) ,
       0 ) ) 
```

OpenDF raises exceptions:

```
opendf.exceptions.python_exception.ParserException: Syntax error at `LexToken(ASSIGN_NODE,'$',1,92)`
```

Could you offer some suggestions to fix it? Thanks and have a good day.

**Comment by guimaraes-tl** [comment]
Dear hankcs,

Thanks for your issue. You can raise as many issues you want, we will be happy to answer them and to improve the code.

There was a bug in the parser, when dealing with assigned names containing spaces between the $ sign and the name.
Hopefully, you will be able to run this example now, after this commit [e4727b5](https://github.com/telepathylabsai/OpenDF/commit/e4727b5f86edb97892f64df29e8d4fd84e4b1717).

Best regards.

**Comment by hankcs** [comment]
Thank you so much. I confirm this bug has been fixed.
